import ProgressBarProvider from "@/component/ProgressBarProvider";
import AppContextProvider from "@/context";
import QueryClientProvider from "@/util/query-client-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="canonical"
          href={"https://fkt-stackbuld-assessment.vercel.app/"}
        />
        <link
          rel="icon"
          href="https://simicart.com/wp-content/uploads/eCommerce-logo.jpg"
        />
      </Head>
      <body className={inter.className}>
        <QueryClientProvider>
          <ProgressBarProvider>
            <AppContextProvider>{children}</AppContextProvider>
          </ProgressBarProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
